name: Feature Request
description: Suggest an idea or feature
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea clearly.
  
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Clear description of the feature you want
      placeholder: |
        We should add Redis caching support to speed up queries...
    validations:
      required: true
  
  - type: textarea
    id: motivation
    attributes:
      label: Motivation & Use Case
      description: Why do you need this feature? What problem does it solve?
      placeholder: |
        Currently, repeated database queries are slow. Redis would cache responses
        and improve page load time from 2s to 500ms.
    validations:
      required: true
  
  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How should this feature be implemented?
      placeholder: |
        1. Add WP_REDIS_* environment variables to .env
        2. Configure Redis connection in wp-config.php
        3. Install redis-cache plugin via Composer
      validations:
      required: false
  
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered alternative approaches?
      placeholder: |
        - Use Redis directly (more complex)
        - Use WP built-in object cache (slower)
        - Use external CDN (more cost)
    validations:
      required: false
  
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Low (Nice to have)
        - Medium (Should have)
        - High (Must have)
    validations:
      required: true
  
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other relevant information?
      placeholder: "Related to issue #123, similar to how WP CLI handles caching..."
    validations:
      required: false
